# Generated by Django 6.0.5 on 2026-05-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, verbose_name='題目')),
                ('option_a', models.CharField(max_length=100, verbose_name='選項 A')),
                ('option_b', models.CharField(max_length=100, verbose_name='選項 B')),
                ('option_c', models.CharField(max_length=100, verbose_name='選項 C')),
                ('option_d', models.CharField(max_length=100, verbose_name='選項 D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正確答案')),
            ],
        ),
    ]
