# Generated by Django 6.0.5 on 2026-05-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='quiz_question',
        ),
    ]
