# Generated by Django 6.0.5 on 2026-05-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='暫無詳解', null=True, verbose_name='題目詳解'),
        ),
    ]
