# Generated by Django 6.0.5 on 2026-05-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('correct_count', models.IntegerField(verbose_name='答對題數')),
                ('wrong_count', models.IntegerField(verbose_name='答錯題數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='測試時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'db_table': 'quiz_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
