# Generated by Django 6.0.5 on 2026-05-23 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='測驗範圍 / 標題')),
                ('quiz_summary', models.CharField(max_length=255, verbose_name='題型統計（如：包含單選 6 題、多選 4 題）')),
                ('score', models.IntegerField(verbose_name='原始得分')),
                ('total_possible_score', models.IntegerField(default=1000, verbose_name='總分（例如圖片中的 1000 分滿分）')),
                ('score_percentage', models.IntegerField(verbose_name='答對率（百分比，如 85）')),
                ('status', models.CharField(choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], default='FAIL', max_length=10, verbose_name='結果狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='測驗日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '歷次挑戰紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
