# Generated by Django 6.0.5 on 2026-05-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='detail_json',
            field=models.TextField(blank=True, null=True, verbose_name='詳細題目快照JSON'),
        ),
    ]
