# Generated by Django 6.0.5 on 2026-05-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizresult_detail_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '易'), ('medium', '中'), ('hard', '難')], default='medium', max_length=10, verbose_name='難易度'),
        ),
        migrations.CreateModel(
            name='WrongQuestionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_count', models.IntegerField(default=0, verbose_name='剩餘冷卻題數')),
                ('wrong_streak', models.IntegerField(default=1, verbose_name='連續答錯次數')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='錯題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'db_table': 'quiz_wrong_tracker',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
