# Generated by Django 6.0.5 on 2026-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='選項 E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, verbose_name='正確答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255, verbose_name='選項 A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255, verbose_name='選項 B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255, verbose_name='選項 C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=255, verbose_name='選項 D'),
        ),
    ]
