"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8@p97%ym1z7p24net#b&54cnrd7q-f($$24g)5=ea-oskz0e-l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ==============================================================================
# Application definition (應用程式定義)
# ==============================================================================

INSTALLED_APPS = [
    # Django 核心內建 App（不可刪除，否則會報 ContentType 錯誤）
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # 第三方擴充套件
    'rest_framework',            
    'rest_framework.authtoken',  
    
    # 你自己的 Django App
    'quiz',                          
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ======================================================================
        # 🚀 終極暴力破解：強制讓 Django 明白「不管是直接找還是帶路徑找，通通給我去這裡翻！」
        # ======================================================================
        'DIRS': [
            os.path.join(BASE_DIR, 'quiz', 'templates'),
            os.path.join(BASE_DIR, 'quiz', 'templates', 'quiz'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'mysite.wsgi.application'


# ==============================================================================
# Database (資料庫設定)
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================================================================
# Password validation (密碼驗證)
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# Internationalization (語系與時區)
# ==============================================================================

# 🎯 修改後：改為台灣語系與台北時區
LANGUAGE_CODE = 'zh-Hant'     # 讓 Django 內建系統（如 Admin 後台）支援繁體中文

TIME_ZONE = 'Asia/Taipei'     # 核心修正：將時區改為台灣本地時間（UTC+8）

USE_I18N = True

USE_TZ = True                 # 保持 True，讓 Django 自動幫資料庫時間做本地時區轉換


# ==============================================================================
# Static files (靜態檔案設定)
# ==============================================================================

STATIC_URL = 'static/'


# ==============================================================================
# Django REST Framework (API 套件設定)
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# ==============================================================================
# Authentication Redirects (登入/登出轉向設定)
# ==============================================================================

# ==============================================================================
# Authentication Redirects (登入/登出轉向設定)
# ==============================================================================

# ==============================================================================
# Authentication Redirects (登入/登出轉向設定)
# ==============================================================================

# 🎯 沒登入的使用者如果亂闖，自動踢回首頁（也就是登入畫面）
LOGIN_URL = '/'

# 🎯 帳密輸入正確、登入成功後，自動跳轉到 /dashboard/ (主畫面)！
LOGIN_REDIRECT_URL = '/dashboard/'

# 🎯 點擊登出後，自動跳轉回首頁（登入畫面）
LOGOUT_REDIRECT_URL = '/'